### ISSUE TITLE
表单设计器问题

### ISSUE THREAD

**Issue by Sailiy** [GavinZhuLei/vue-form-making#1]
您好，我最近也在做类似表单设计器的东西。用v-for这种方法根据类型创建表单item会导致生成表单item的判断条件过多，如果表单过大，后期随着需求增加会一直增加新的组件，这种设计方式都会产生性能问题。看了你们的代码，很多还是值得借鉴的，如果有兴趣。
我的项目在[这里](https://github.com/Sailiy/vv-form-design)，刚开始研究开发了一个demo，希望可以一起交流

**Comment by GavinZhuLei** [comment]
@Sailiy 对的，目前的问题就是在组件逐渐增加的时候会持续在v-for中添加组件，暂时没有想到更好的解决办法，有好的想法可以一起交流

**Comment by Sailiy** [comment]
你们可以考虑使用render方法，只要组件在全局或者局部注册过的输入组件名都能被渲染出来
我这里的拖动是自己写的，还有一些小问题，
官方文档：https://cn.vuejs.org/v2/guide/render-function.html
主要代码文件：https://github.com/Sailiy/vv-form-design/blob/master/src/views/Editor/EditMain.vue

`
render: function (h) { // h 为 createElement 函数，接受三个参数
    return h('el-form', {
      props: {
        labelWidth: '80px'
      },
      nativeOn: {
        dragover: this.handleOnRootDragOver,
        drop: this.handleOnRootDrop
      },
      ref: 'FForm'
    }, this.allComponents.map((component, index) => {
      if (!component.hasOwnProperty('isActive')) this.$set(component, 'isActive', false)
      return h(component.name, {
        directives: [
          { name: 'masking' }
        ],
        attrs: {
          'data-index': index,
          draggable: true
        },
        class: {
          active: component.isActive
        },
        nativeOn: {
          click: (e) => {
            this.handleItemClick(e, index)
          },
          dragstart: this.childrenDragStart
        },
        ref: 'formItem' + index
      })
    }))
  }
`

**Comment by GavinZhuLei** [comment]
后面可以考虑使用render
