### ISSUE TITLE
栅格布局字段在创建后移动位置会出现指示线循环上下跳动问题

### ISSUE THREAD

**Issue by moonrailgun** [GavinZhuLei/vue-form-making#100]
其他的组件没有出现这种情况

重现方式:
拖入一个栅格布局组件 拖入任意几个其他任意组件。
点击栅格布局组件，拖动 移动handler 到其他组件。红色指示线会循环上下移动

环境。演示demo: http://form.xiaoyaoji.cn/basic-version/#/zh-CN/

**Comment by GavinZhuLei** [comment]
栅格布局组件在没有拖入组件的时候确实存在这个问题，

目前可以通过设置 draggable 的 animation:0 来让上下循环移动效果没那么明显
