### ISSUE TITLE
在vue 国际化环境中会导致原本国际化失效

### ISSUE THREAD

**Issue by wangvito** [GavinZhuLei/vue-form-making#103]
vue-i18n":版本6.1.0",国际化失效,导致显示$t中的英文

**Comment by GavinZhuLei** [comment]
http://docs.form.xiaoyaoji.cn/guide.html#%E5%9C%A8%E5%A4%9A%E8%AF%AD%E8%A8%80%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8
