### ISSUE TITLE
表单控件如何支持移动端？

### ISSUE THREAD

**Issue by mexhfl** [GavinZhuLei/vue-form-making#104]

**Comment by GavinZhuLei** [comment]
目前使用的是 element 组件，对移动端兼容不是很好，可以更改组件库

**Comment by mexhfl** [comment]
> 目前使用的是 element 组件，对移动端兼容不是很好，可以更改组件库

能不能新增一套组件库，自动生成两套表单，用户访问的时候自动匹配PC/移动，工作量有多大？

**Comment by GavinZhuLei** [comment]
https://github.com/GavinZhuLei/vue-form-making/issues/105
