### ISSUE TITLE
这开源跟花钱买有什么区别？

### ISSUE THREAD

**Issue by lanboss** [GavinZhuLei/vue-form-making#106]
没看明白release和源码版跟目前这里看到源码的版本有什么区别？（release和2000购买的那个我知道，但现在有看到公开源码）

**Comment by GavinZhuLei** [comment]
基础版本和开源版本是保持一致的，开源版本使用 LGPL 协议，所有修改的代码，涉及修改部分的额外代码和衍生的代码都必须采用LGPL协议进行开源，详细可以查看 LGPL 协议内容，如果需要用于商业，不使用 LGPL 协议开源，可以联系我们[购买授权](http://form.xiaoyaoji.cn/pricing/)。
