### ISSUE TITLE
使用远端数据的问题

### ISSUE THREAD

**Issue by guankailun** [GavinZhuLei/vue-form-making#107]
1.使用远端数据的时候，好像不能预览，fm-making-form组件不支持remote属性
2.使用远端数据的时候，如果在fm-making-form里面点一下预览的功能，到了fm-generate-form组件之后，原本正常的选项变成空了
请问下是我没掌握正确的姿势还是说本身就会有这些问题

**Comment by GavinZhuLei** [comment]
预览暂未支持 remote。
正确姿势： http://docs.form.xiaoyaoji.cn/manual/remote-funcs.html
