### ISSUE TITLE
远端数据获取问题

### ISSUE THREAD

**Issue by liujiaang** [GavinZhuLei/vue-form-making#112]
每次生成表单，远程方法名都会不一样，对应的远端数据怎么绑定？怎么样才能动态配置上远程方法？

**Comment by liuzm7188** [comment]
自己开发接口呗 固定方法名 就可以了 用到的页面 配置remoteFunc  
![image](https://user-images.githubusercontent.com/20579366/99494901-c15ad000-29ac-11eb-80e5-719e56cca8c0.png)
