### ISSUE TITLE
样式污染问题

### ISSUE THREAD

**Issue by ping40** [GavinZhuLei/vue-form-making#114]
采用  <style src="form-making/dist/FormMaking.css" />   污染 页面别的样式。

采用  <style src="form-making/dist/FormMaking.css"  scoped />, 别的样式正常，但是 表单设计器的页面  不正常。

翻看  Issue,但是 dist 包里面 没有 cover.css.

谢谢

**Comment by GavinZhuLei** [comment]
已经优化，外层用 .fm-style 类名区分名称空间
