### ISSUE TITLE
系统集成问题

### ISSUE THREAD

**Issue by upcwangying** [GavinZhuLei/vue-form-making#125]
按照此[方式](https://github.com/GavinZhuLei/vue-form-making/blob/master/docs/guide.md#import-element)进行集成，没有正确显示

![KE{7Z_MEYK05I~@W{1W`_(L](https://user-images.githubusercontent.com/19725091/93032436-384db280-f664-11ea-8b8c-2348d11f8451.png)

**Comment by GavinZhuLei** [comment]
需要给组件设置高度

https://github.com/GavinZhuLei/vue-form-making/blob/master/docs/guide.md#makingform

**Comment by upcwangying** [comment]
@GavinZhuLei 已经设置了高度

**Comment by upcwangying** [comment]
![_W94XOC1YBGRQ9_PYB@KDNO](https://user-images.githubusercontent.com/19725091/93036626-fd06b000-f672-11ea-924d-4e1945493558.png)

**Comment by GavinZhuLei** [comment]
不起作用吗？ 看下样式什么地方没有对，设计器渲染是出来了的，只是没有高度

**Comment by upcwangying** [comment]
因为这里高度为0

![KAVCIL){MQ9DG{Y2E`LXNHF](https://user-images.githubusercontent.com/19725091/93036972-d7c67180-f673-11ea-8561-df50f81270f0.png)
