### ISSUE TITLE
引入后样式错乱，如何调整页面样式。

### ISSUE THREAD

**Issue by Hwongyohong** [GavinZhuLei/vue-form-making#127]
![bd336e6259c3d9d42eb903471f2eb5b](https://user-images.githubusercontent.com/30889398/94381256-4ffc5f00-016b-11eb-956e-d2bba250eae9.png)

**Comment by liuzm7188** [comment]
右侧不可以调整吗 一行多个 用栅格布局

**Comment by Dason-zdc** [comment]
遇到了同样的问题，请问解决了吗

**Comment by adingGit** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到，有时间的时候我会尽快给您回复。、。、。、。韦夫廷

**Comment by GavinZhuLei** [comment]
可以调整元素padding
