### ISSUE TITLE
栅格布局 用于自己开发的组件，拖动时提示如下错误 需要怎么解决呢？

### ISSUE THREAD

**Issue by liuzm7188** [GavinZhuLei/vue-form-making#133]
![image](https://user-images.githubusercontent.com/20579366/99494475-09c5be00-29ac-11eb-8789-1fccea8b5260.png)

**Comment by fuzi1996** [comment]
这是之前开源版本的问题，目前已修复。
原因：在使用vue-draggable时，如果子组件中包含`transition-group`标签，就不要将draggable的`no-transition-on-drag`置为true
