### ISSUE TITLE
多行文本回显 无法换行问题

### ISSUE THREAD

**Issue by liuzm7188** [GavinZhuLei/vue-form-making#136]
![image](https://user-images.githubusercontent.com/20579366/100199413-2166ee80-2f38-11eb-8db7-828d60b458e7.png)
![image](https://user-images.githubusercontent.com/20579366/100199388-190eb380-2f38-11eb-8131-adf189c6adce.png)
怎么解决多行文本回显 无法换行问题

**Comment by GavinZhuLei** [comment]
可以通过多行文本进行回显

**Comment by xiemf** [comment]
<pre><pre>包裹

**Comment by xiemf** [comment]
用pre标签包括

**Comment by adingGit** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到，有时间的时候我会尽快给您回复。、。、。、。韦夫廷
