### ISSUE TITLE
根据参数判别远端数据获取

### ISSUE THREAD

**Issue by lingkejia** [GavinZhuLei/vue-form-making#137]
使用select等组件配置远端数据只能配置固定方法名，若要在一个表单内多个select获取数据就要对应多个方法，但多个方法其实只是接口地址不同，其次要想实现就必须动态生成代码还要做额外的工作，能否在回调函数中加入参数的方式来解决这个问题呢？比如select中定义一个getData(1)的方法，那么getData方法体内根据业务自定判定获取数据的接口？

**Comment by GavinZhuLei** [comment]
你可以定义一个公用方法通过不同的参数传入获取数据，然后在设计器配值的方法中调用该方法即可

**Comment by lingkejia** [comment]
没错，现在的思路就是通过参数来判定，我定义一个公共方法getData(type)，在设计器中我应该配置方法名称为getData(1)就可以，但实际情况是设计器中的方法不能添加参数，只能配置方法名，如果我配置了getData(1)，在生成的代码中就会变成 getData(1) (resolve),也不能配置getData(1,callback)

**Comment by majingtao** [comment]
有什么解决办法吗，我们也是需要这样的功能
