### ISSUE TITLE
表单字段联动问题

### ISSUE THREAD

**Issue by hyshzx** [GavinZhuLei/vue-form-making#139]
现在有 输入框A 和 输入框B，B的值可以自己填，也可以根据A的值，然后根据一定的规则自动生成或者自动选择。请问现在有这样的功能么？谢谢解答。

**Comment by hyshzx** [comment]
问题升级一下。怎么表单设计的时候，就通过js增强实现这样的逻辑，在generateForm阶段取得这样的js逻辑，实现这样的效果，谢谢。

**Comment by GavinZhuLei** [comment]
目前只能在GenerateForm中添加逻辑，后面会进行升级，在设计器中可以定义js

**Comment by majingtao** [comment]
现在也是急需这样的功能。。加油

**Comment by yasz** [comment]
这个功能很重要，期待早日开发！

**Comment by GavinZhuLei** [comment]
https://www.yuque.com/ln7ccx/ntgo8q/ni8vfm
