### ISSUE TITLE
字段文字没有开发完全

### ISSUE THREAD

**Issue by zhongshanhao** [GavinZhuLei/vue-form-making#140]
![ES$ FNL{XIRX%UIM91~A6{A](https://user-images.githubusercontent.com/19641047/104295341-4cfb6380-54fb-11eb-880d-31c6818da62b.png)
不能够设置文字，需要将“This is a text”替换成其他文字，

**Comment by GavinZhuLei** [comment]
会尽快进行修复，目前可以通过修改 json 中 defaultValue 来实现

**Comment by zhongshanhao** [comment]
> 会尽快进行修复，目前可以通过修改 json 中 defaultValue 来实现

ok，感谢

**Comment by atdow** [comment]
> ![ES$ FNL{XIRX%UIM91~A6{A](https://user-images.githubusercontent.com/19641047/104295341-4cfb6380-54fb-11eb-880d-31c6818da62b.png)
> 不能够设置文字，需要将“This is a text”替换成其他文字，

The text component added edit function of defaultValue already!

**Comment by fuzi1996** [comment]
该问题新版本已解决
