### ISSUE TITLE
vue3 引用组件

### ISSUE THREAD

**Issue by keke599** [GavinZhuLei/vue-form-making#149]
无法找到模块“form-making”的声明文件。“d:/bdsz/bdsz-web-research/node_modules/form-making/dist/FormMaking.common.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/form-making` (如果存在)，或者添加一个包含 `declare module 'form-making';` 的新声明(.d.ts)文件ts(7016)
module "d:/bdsz/bdsz-web-research/node_modules/form-making/dist/FormMaking.common"

**Comment by zoubeihua** [comment]
老哥：你的问题解决了吗 ？ 我是vite+vue3.0 也是遇到同样的问题

**Comment by GavinZhuLei** [comment]
目前还不支持vue3.0
