### ISSUE TITLE
老哥能支持excel表格那种拖拽元素布局吗

### ISSUE THREAD

**Issue by LYJH1314** [GavinZhuLei/vue-form-making#15]
老哥能支持excel表格那种拖拽元素布局吗？

**Comment by LYJH1314** [comment]
老哥有计划去做excel表格那种拖拽元素布局吗

**Comment by GavinZhuLei** [comment]
excel页面布局吗？最好可以提供下效果展示

**Comment by MetSystem** [comment]
![image](https://user-images.githubusercontent.com/7943054/53148850-f3c47700-35e6-11e9-8c68-69d55982d6a7.png)

**Comment by MetSystem** [comment]
应该类似这种效果
