### ISSUE TITLE
vue项目中引用后报错

### ISSUE THREAD

**Issue by fengqijie** [GavinZhuLei/vue-form-making#154]
大佬，我在项目中引用了您的组件，但是报错“vue.esm.js?a026:1906 TypeError: t.$t is not a function
    at Proxy.eval (FormMaking.common.js?03b1:37)” 您知道是怎么回事不？ 这是我的使用，干净的页面~ `<template>
  <div>
    <fm-making-form
      ref="makingform"
      style="height: 500px;"
      preview
      generate-code
      generate-json
    >
      <template slot="action"> </template>
    </fm-making-form>
  </div>
</template>

<script>
import Vue from "vue";
import { GenerateForm, MakingForm } from "form-making";
import "form-making/dist/FormMaking.css";
Vue.component(GenerateForm.name, GenerateForm);
Vue.component(MakingForm.name, MakingForm);

export default {};
</script>`

**Comment by GavinZhuLei** [comment]
https://github.com/GavinZhuLei/vue-form-making/blob/master/docs/guide.zh-CN.md#%E5%9C%A8%E5%A4%9A%E8%AF%AD%E8%A8%80%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by fengqijie** [comment]
感谢大佬，已解决~
