### ISSUE TITLE
自定义组件的readonly、disabled等属性不生效

### ISSUE THREAD

**Issue by isooc** [GavinZhuLei/vue-form-making#155]
内部表单元素没有继承到这个属性，所以文档里的这个属性是用来干嘛的？还是我用错了呢
`customFields: [
        {
          name: '自定义组件',
          el: 'custom-width-height',
          options: {
            defaultValue: {
              width: 100,
              height: 100
            },
            customClass: '',
            labelWidth: 0,
            isLabelWidth: false,
            hidden: false,
            disabled: true, // 无效
            dataBind: true,
            pattern: ''
          },
        }
]`

**Comment by GavinZhuLei** [comment]
高级版本可以给我们提交工单或者联系我们技术支持客服，qq:1691620947
