### ISSUE TITLE
安卓内嵌webview加载表单设计器中GenerateAntdForm组件无法执行执行js

### ISSUE THREAD

**Issue by ht176** [GavinZhuLei/vue-form-making#158]
安卓程序webview内加载GenerateAntdForm组件时js无法被执行。
![image](https://user-images.githubusercontent.com/76193063/149463138-8ca46590-a8b2-49f3-af15-8ea981c3c9b1.png)
![image](https://user-images.githubusercontent.com/76193063/149463310-5e907246-71e5-4d2a-82bf-dd7738818aaa.png)
图一为浏览器中使用，图二为安卓webvview中使用
{"list":[{"type":"input","icon":"icon-input","options":{"width":"","defaultValue":"","required":false,"requiredMessage":"","dataType":"","dataTypeCheck":false,"dataTypeMessage":"","pattern":"","patternCheck":false,"patternMessage":"","validatorCheck":false,"validator":"","placeholder":"","customClass":"","disabled":false,"labelWidth":100,"isLabelWidth":false,"hidden":false,"dataBind":true,"showPassword":false,"remoteFunc":"func_lmlcc2bf","remoteOption":"option_lmlcc2bf"},"events":{"onChange":"","onFocus":"","onBlur":""},"name":"单行文本","key":"lmlcc2bf","model":"Name","rules":[]},{"type":"select","icon":"icon-select","options":{"defaultValue":"Option 2","multiple":false,"disabled":false,"clearable":false,"placeholder":"","required":false,"requiredMessage":"","validatorCheck":false,"validator":"","showLabel":false,"width":"","options":[{"value":"Option 1"},{"value":"Option 2"},{"value":"Option 3"},{"value":"新选项"}],"remote":false,"remoteType":"datasource","remoteOption":"option_3zskbw8q","filterable":false,"remoteOptions":[],"props":{"value":"value","label":"label"},"remoteFunc":"func_3zskbw8q","customClass":"","labelWidth":100,"isLabelWidth":false,"hidden":false,"dataBind":true,"tableColumn":false},"events":{"onChange":"her5jwuh","onFocus":"","onBlur":""},"name":"下拉选择框","key":"3zskbw8q","model":"select_3zskbw8q","rules":[]}],"config":{"labelWidth":100,"labelPosition":"right","size":"small","customClass":"","ui":"antd","layout":"horizontal","labelCol":3,"width":"100%","hideLabel":false,"hideErrorMessage":false,"eventScript":[{"key":"mounted","name":"mounted","func":"\nthis.setData({\n  Name: '12345'\n})"},{"key":"her5jwuh","name":"onChange_her5jwuh","func":"alert(123456)"}],"dataSource":[{"key":"upload","name":"Get Upload Token","url":"http://tools-server.making.link/api/uptoken","method":"GET","auto":true,"responseFunc":"return res.uptoken;"},{"key":"getoptions","name":"Get Options","url":"http://tools-server.making.link/api/new/options","method":"GET","auto":true,"responseFunc":"return res.data;"}]}}

**Comment by GavinZhuLei** [comment]
高级版本可以联系我们的技术支持客服
