### ISSUE TITLE
i18n报错

### ISSUE THREAD

**Issue by Aiye** [GavinZhuLei/vue-form-making#161]
![image](https://user-images.githubusercontent.com/9073364/176863024-e55869bf-660e-406a-af87-6b465027aa37.png)

**Comment by Jean1988** [comment]
你好， 请问这个问题解决了吗 我今天也遇到了

**Comment by GavinZhuLei** [comment]
``` json
"vue": "2.6.14"
"vue-template-compiler": "2.6.14"
```
