### ISSUE TITLE
商业使用问题

### ISSUE THREAD

**Issue by yixiu025** [GavinZhuLei/vue-form-making#162]
从master上的[README.md](https://github.com/GavinZhuLei/vue-form-making/blob/master/README.md)文档以及[LICENSE](https://github.com/GavinZhuLei/vue-form-making/blob/master/LICENSE)来看，贵项目标识的LICENSE是MIT协议，但是为什么ISSUE里面的回复告知的LGPL协议呢？是项目上面写错了吗？还是说开源版本就是MIT协议呢？

**Comment by GavinZhuLei** [comment]
你好，开源版本目前使用 MIT 协议，之前使用的LGPL，目前已经更新到 MIT

**Comment by yixiu025** [comment]
好的，谢谢。
