### ISSUE TITLE
请问添加数据源界面在哪？

### ISSUE THREAD

**Issue by zhoufanglu** [GavinZhuLei/vue-form-making#165]
![image](https://user-images.githubusercontent.com/24451091/221073249-c5f46ea0-1a1d-41b5-9ca3-fa021e23717a.png)
如题

**Comment by GavinZhuLei** [comment]
你好，这里是基础开源版本，没有提供数据源管理功能，可以前往高级版本查看：
https://form.making.link/

**Comment by zhoufanglu** [comment]
> 你好，这里是基础开源版本，没有提供数据源管理功能，可以前往高级版本查看： https://form.making.link/

我想问下 如果是基础版本 远端数据怎么出发这个函数
<img width="298" alt="image" src="https://user-images.githubusercontent.com/24451091/221459724-19e28c47-17b1-43c9-ba92-4624184bc33f.png">

**Comment by GavinZhuLei** [comment]
该方法会在组件created生命周期中自动调用。
https://form.making.link/docs/manual/options.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E5%87%BD%E6%95%B0

**Comment by zhoufanglu** [comment]
> 该方法会在组件created生命周期中自动调用。 https://form.making.link/docs/manual/options.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E5%87%BD%E6%95%B0

好像没有调用, 在新建表单中
<img width="454" alt="image" src="https://user-images.githubusercontent.com/24451091/227485861-fc77bc32-eb75-4f96-b5c0-cb890e0e4fdf.png"> 
--- 
构造器配置的属性
![image](https://user-images.githubusercontent.com/24451091/227486167-6b4960fb-c3b4-4874-abcd-44531fb327c9.png)
--- 

报错
`Cannot read properties of undefined (reading 'getSelect')"
`
