### ISSUE TITLE
同时渲染5个表格及以上, 页面会直接卡掉!

### ISSUE THREAD

**Issue by Jerry-CodeHub** [GavinZhuLei/vue-form-making#174]
同时渲染5个表格及以上, 页面会直接卡掉, 内存占用达到1G以上, 请问这个是渲染有办法解决嘛!

**Comment by Jerry-CodeHub** [comment]
> 同时渲染5个表格及以上, 页面会直接卡掉, 内存占用达到1G以上, 请问这个是渲染有办法解决嘛!


之前的同事买的收费版本, 如果可以解决还望告知一下! 感谢🙏

**Comment by GavinZhuLei** [comment]
更新到最新版本，如果还有问题可以联系我们技术支持：[https://work.weixin.qq.com/kfid/kfcc7afa8cab42b568f](https://work.weixin.qq.com/kfid/kfcc7afa8cab42b568f)

**Comment by Jerry-CodeHub** [comment]
> 更新到最新版本，如果还有问题可以联系我们技术支持：https://work.weixin.qq.com/kfid/kfcc7afa8cab42b568f

好的谢谢, 已联系!
