### ISSUE TITLE
图片上传组件不能 正常显示

### ISSUE THREAD

**Issue by ZbWeb** [GavinZhuLei/vue-form-making#21]
我的JSON中含有图片上传组件，但是表单渲染的时候图片上传组件不能正常显示，只显示‘图片’两个字，没有上传按钮。

**Comment by GavinZhuLei** [comment]
[https://github.com/GavinZhuLei/vue-form-making/blob/master/doc/imgupload.md](https://github.com/GavinZhuLei/vue-form-making/blob/master/doc/imgupload.md)

**Comment by ZbWeb** [comment]
恩，问题解决了，resolve()的时候必须要传一个值。
