### ISSUE TITLE
GenerateFormItem文件中的计数器的问题，好像是bug

### ISSUE THREAD

**Issue by wuchubuzai2018** [GavinZhuLei/vue-form-making#23]
这个文件中我看其他控件都是用dataModel去绑定v-model,但是28行中的计数器用了defaultValue，这个是不是bug。代码如下
<template v-if="widget.type == 'number'">
      <el-input-number 
        v-model="widget.options.defaultValue" 
        :style="{width: widget.options.width}"
        :step="widget.options.step"
        controls-position="right"
      ></el-input-number>
</template>

在我的环境有问题，但是我改成
 v-model="dataModel" 解决了我的问题，但是在你的演示环境中好像没有这个问题呢

**Comment by GavinZhuLei** [comment]
是的 感谢提醒
