### ISSUE TITLE
怎样在设计器中取消日期选择控件（datarange）的日期选择面板联动

### ISSUE THREAD

**Issue by fenglier** [GavinZhuLei/vue-form-making#24]

**Comment by fenglifenglifengli** [comment]
![image](https://user-images.githubusercontent.com/30134217/51510737-44ef1880-1e39-11e9-8d69-4104d22da539.png)

**Comment by fenglifenglifengli** [comment]
![image](https://user-images.githubusercontent.com/30134217/51510777-723bc680-1e39-11e9-85d8-2827f4cdfbca.png)

**Comment by GavinZhuLei** [comment]
没有理解到你的描述是什么意思

**Comment by fenglifenglifengli** [comment]
就是取消日期面板的联动。就是我点击右边这个日期选择的“》”时，左边那个日期选择面板不跟着动。

![image](https://user-images.githubusercontent.com/30134217/51528422-9adfb280-1e71-11e9-892a-316ec8c85ad5.png)

    其实，在原本的标签里面只用加一个unlink-planels就行了。我不晓得用json控制表单时，怎样操作。
