### ISSUE TITLE
引入到我的项目后，每次拖拽一个字段到中间区域时，浏览器就会打开一个页面

### ISSUE THREAD

**Issue by 1253062595** [GavinZhuLei/vue-form-making#25]
![default](https://user-images.githubusercontent.com/13758734/52621503-68f6c480-2ee2-11e9-9a25-61aa7871dd92.png)
我把vue-form-making的源文件引入到我的项目中，在绘制form的时候，每从左侧拖拽一个基础字段或其他字段到中间区域时，浏览器就会新打开一个页面，搜索我选择的字段。比如我添加了一个单行文本，那浏览器就会新打开一个界面来搜索单行文本，请问这是怎么回事？要怎么解决呢？

**Comment by zcsoft-guodeliang** [comment]
你好，请问一下 你怎么把这个设计器在html中引用？ 这样对吗？因为没搞过vue
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8">
     <script src="https://unpkg.com/vue/dist/vue.js"></script>
	 <script src="./FormMaking.umd.js"></script>
	 <link rel="stylesheet" href="./FormMaking.css">
  </head>
  <body>
 
	  <div id="app">
		<template>
		<fm-making-form>
		
		</fm-making-form>
		</template>
	  </div>
 
  </body>
   <script>
   
	Vue.component(FormMaking.MakingForm.name, FormMaking.MakingForm);
 
	
	 
	 new Vue({el:'#app'}) ;
	
    </script>
  </html>

**Comment by GavinZhuLei** [comment]
生成代码里面可以查看到html中引用方法

**Comment by lfeiniao** [comment]
，每从左侧拖拽一个基础字段或其他字段到中间区域时，浏览器就会新打开一个页面，搜索我选择的字段.我也遇到这个问题，和浏览器有关系，火狐的就有这个问题。

**Comment by GavinZhuLei** [comment]
请检查下版本，该问题已经修复

**Comment by 1253062595** [comment]
已经更新了最新代码，完美解决了火狐拖拽搜索问题，谢谢 @GavinZhuLei
