### ISSUE TITLE
表单保存后如何回显

### ISSUE THREAD

**Issue by yingbo-wu** [GavinZhuLei/vue-form-making#26]
表单保存json，如何把json，include并回显？

**Comment by GavinZhuLei** [comment]
提供有 setJson 方法

**Comment by SamHz** [comment]
@GavinZhuLei 没有找到有setJson的方法，显示是可以，但是WidgetForm这里有一个问题当我加载Ajax数据后，他过快的加载组件，我在页面加Loading也不行，它会先加载组件再加入我的数据，做成我要在WidgetForm的mounted中$nextTick来等待数据，这样也只是能达到数据回显，但实际还是先报了错再加载的，这样一大堆错出来，后面如果有其他错就肯定会晕掉，有没有办法能select:sync这里不要在创建时就加载呢？

**Comment by GavinZhuLei** [comment]
> @GavinZhuLei 没有找到有setJson的方法，显示是可以，但是WidgetForm这里有一个问题当我加载Ajax数据后，他过快的加载组件，我在页面加Loading也不行，它会先加载组件再加入我的数据，做成我要在WidgetForm的mounted中$nextTick来等待数据，这样也只是能达到数据回显，但实际还是先报了错再加载的，这样一大堆错出来，后面如果有其他错就肯定会晕掉，有没有办法能select:sync这里不要在创建时就加载呢？

你可以把错误信息贴出来，看下是原因导致的

**Comment by SamHz** [comment]
@GavinZhuLei 我这边已经解决了
由于回显数据时，没有选中所以会导致select那里为Null，在WidgetForm加个判断让他在没有值时不显示
![image](https://user-images.githubusercontent.com/13477017/53785104-59ebbb00-3f52-11e9-80cf-7a90354684df.png)
