### ISSUE TITLE
关于ace的问题

### ISSUE THREAD

**Issue by dabaoabc** [GavinZhuLei/vue-form-making#30]
组件运行的时候为啥会引入这个js文件http://tools.xiaoyaoji.cn/form/lib/ace/src/ace.js
因为我们是内部系统，是连不上外网的，是否可以考虑转成相对路径

**Comment by GavinZhuLei** [comment]
引入ace.js是为了展示代码用的，这块我优化下

**Comment by mcc-like-thinking** [comment]
@GavinZhuLei vue项目通过npm安装，项目运行后提示ace.js文件找不到

**Comment by GavinZhuLei** [comment]
> @GavinZhuLei vue项目通过npm安装，项目运行后提示ace.js文件找不到

已经更新npm包和文档，版本@1.1.14
