### ISSUE TITLE
关于异步拉取数据问题

### ISSUE THREAD

**Issue by dabaoabc** [GavinZhuLei/vue-form-making#31]
`async created () {
        this.jsonData = await this.getJson();
 },`
如果是异步拉取jsonData，配置的default值会不显示，非异步拉则没有这个问题

**Comment by GavinZhuLei** [comment]
getJSON() 不是异步方法

**Comment by dabaoabc** [comment]
getJSON()是我这边定义的从服务器拉数据的一个方法

**Comment by GavinZhuLei** [comment]
拉取到数据后 使用setJSON() 方法把json注入到设计器里面

**Comment by yuana1** [comment]
@GavinZhuLei 
是用fm-generate-form的时候异步获取表单json，这种情况下， 表单校验无效，然后checkbox点击其中一个会全部选择
![image](https://user-images.githubusercontent.com/7308509/54877089-d2a8ad80-4e54-11e9-9d53-7d5a31bcd4c0.png)
