### ISSUE TITLE
栅格布局

### ISSUE THREAD

**Issue by yangYangxs** [GavinZhuLei/vue-form-making#35]
把控件拖拽到中间后再往栅格布局里面拖，控件拖不进去

**Comment by GavinZhuLei** [comment]
请提供下版本号，重现步骤

**Comment by yangYangxs** [comment]
已经解决  是那个draggable的sort事件优先了放进栅格的事件  可以让栅格禁止排序就能放进去  也可以让拖动的组件的宽度小于栅格的宽度也能放进去，版本应该是最新的那个版本

**Comment by youchenglei** [comment]
我也遇到这个问题了，请问你是怎么单独禁止栅格的排序的

**Comment by yangYangxs** [comment]
我是把sort设置为了false,,但是最后我是用的第二个方法  就是推拽的时候把推拽的单位比例缩小就行了

**Comment by GavinZhuLei** [comment]
提供下 重现步骤 我这边了解下

**Comment by youchenglei** [comment]
打开演示网站 http://tools.xiaoyaoji.cn/form/#/，拖动一个栅格布局到页面，再随便拖动一个控件到页面中与栅格布局同级，然后把该控件往栅格布局中拖动，会出现拖不进去的现象

**Comment by GavinZhuLei** [comment]
问题我这边清楚了

**Comment by GavinZhuLei** [comment]
已修复
