### ISSUE TITLE
无法拖动到中间区域

### ISSUE THREAD

**Issue by cmkcmk181** [GavinZhuLei/vue-form-making#36]
拖动到中间区域不显示控件

**Comment by GavinZhuLei** [comment]
请提供下版本号，重现步骤

**Comment by cmkcmk181** [comment]
我直接访问 http://tools.xiaoyaoji.cn/form/#/ 这个地址的，拖动进不了中间区域，chrome浏览器

**Comment by GavinZhuLei** [comment]
> 我直接访问 http://tools.xiaoyaoji.cn/form/#/ 这个地址的，拖动进不了中间区域，chrome浏览器

我这边是正常的

**Comment by cmkcmk181** [comment]
我换了几个浏览器都不行

**Comment by GavinZhuLei** [comment]
> 我换了几个浏览器都不行

提供下 系统和浏览器版本

**Comment by cmkcmk181** [comment]
360极速和QQ浏览器不行

**Comment by GavinZhuLei** [comment]
chrome firefox 是没有问题的，你这两个浏览器是不是设置有问题

**Comment by cmkcmk181** [comment]
没有，好像第三方的浏览器都不行，可能和Chromium内核有关系吧

**Comment by buffonly** [comment]
用360和QQ浏览器不行，，关键不能强制客户使用chrome和firefox

**Comment by ycyreddevil** [comment]
我用谷歌和360不行

**Comment by GavinZhuLei** [comment]
此问题已经修复
