### ISSUE TITLE
ace is not defined?

### ISSUE THREAD

**Issue by lliiuu** [GavinZhuLei/vue-form-making#46]
通过npm安装，点击生成代码和生成json都会报ace is not defined，能否告知这个报错问题的解决的方法，谢谢

**Comment by GavinZhuLei** [comment]
```
<!-- 需要在设计器中预览代码需要引入ace.js库 -->
<script src="https://unpkg.com/form-making/public/lib/ace/src-min/ace.js"></script>
```

**Comment by lliiuu** [comment]
你好，我是通过npm 包安装的，应该怎么引入呢

**Comment by GavinZhuLei** [comment]
`import 'form-making/public/lib/ace/src-min/ace.js'`

**Comment by lliiuu** [comment]
你好，我这样引入会报错，但是文件路径也是对的，

Failed to compile.

./node_modules/form-making/public/lib/ace/src-min/ace.js
Module not found: Error: Can't resolve '../../lib/lang' in 'C:\Users\11011\Desktop\vue\assistant\assistant-web\node_modules\form-making\public\lib\ace\src-min'

**Comment by GavinZhuLei** [comment]
试试这个呢
`import 'form-making/public/lib/ace/src-min-noconflict/ace.js'`

**Comment by lliiuu** [comment]
可以了，谢谢

**Comment by mayuanyuancode** [comment]
请问 import 'form-making/public/lib/ace/src-min-noconflict/ace.js'， src-min-noconflict在路径中真实有的吗？我的node_module/form-making/public/lib/ace 下没有src-min-moconflict，所以还会报错

**Comment by comkis** [comment]
![image](https://user-images.githubusercontent.com/28430876/82626740-278fb180-9c1b-11ea-8976-b4a5a2a24634.png)
可以用，但是console里面有这个报错，不知道有什么影响
