### ISSUE TITLE
完整引入 FormMaking.css 影响element ui 样式

### ISSUE THREAD

**Issue by lxf-shawn** [GavinZhuLei/vue-form-making#51]
比如：字体样式font-family就覆盖了element ui原有的，
![image](https://user-images.githubusercontent.com/16770095/58774413-efe7be00-85f3-11e9-9ec1-e4ffd0641aac.png)

**Comment by GavinZhuLei** [comment]
font-family 没什么影响的

**Comment by lxf-shawn** [comment]
不止font-family，还有很多样式都变了， 有没有方法可以不影响elment ui ？部分引入 FormMaking.css还是会影响到elment ui,

**Comment by GavinZhuLei** [comment]
/src/styles/cover.scss，这个地方是全部重写的一些样式

**Comment by lxf-shawn** [comment]
好的，谢谢。
