### ISSUE TITLE
单选框组设置显示标签，未选中任一项，生成json时，默认值是“选项1”

### ISSUE THREAD

**Issue by lincimy** [GavinZhuLei/vue-form-making#53]

**Comment by GavinZhuLei** [comment]
没有这个问题啊

**Comment by lincimy** [comment]
抱歉，触发场景没有描述清楚，触发场景应是如下所述：


1.选择单选框组组件，勾选“选项1”项为默认选择项；



2.删除“选项1”项，未重新勾选默认的选项；



3.点击“生成json”，此时json中设置radio的默认值为“选项1”。



------------------
微笑向前，遇见更美好的自己~~

 




------------------ 原始邮件 ------------------
发件人: "GavinZhuLei"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 下午4:06
收件人: "GavinZhuLei/vue-form-making"<vue-form-making@noreply.github.com>;
抄送: "枫叶"<1019262376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [GavinZhuLei/vue-form-making] 单选框组设置显示标签，未选中任一项，生成json时，默认值是“选项1” (#53)




没有这个问题啊

**Comment by GavinZhuLei** [comment]
收到
