### ISSUE TITLE
表单域的只读属性，没有效果

### ISSUE THREAD

**Issue by zhangchi1002** [GavinZhuLei/vue-form-making#57]
设置了readonly为true，仍然可以编辑。disabled倒是有用

**Comment by GavinZhuLei** [comment]
提供下问题的字段和重现步骤

**Comment by zhangchi1002** [comment]
就是在演示页面上http://tools.xiaoyaoji.cn/form/#/ ，导入JSON，然后添加"readonly": true，没有效果的

**Comment by zhangchi1002** [comment]
我看之前文本框上面也没有设置disabled的地方，最近加上了。。。我在QQ给你留言啦，里面有截图。
