### ISSUE TITLE
打开新tab问题

### ISSUE THREAD

**Issue by tianxia0079** [GavinZhuLei/vue-form-making#67]
拖拽组件时候，如果不不放到布局区域，会打开新tab
这个通过升级版本可以解决吗 我看sortable.js作者好像修复了
https://github.com/SortableJS/Sortable/issues/1012

**Comment by GavinZhuLei** [comment]
提供下你使用的版本号和导致问题的操作步骤

**Comment by tianxia0079** [comment]
最新版本
360急速浏览器，拖住一个组件，不要拖到布局区域，拖拽小小一段距离松开，就打开新tab

**Comment by GavinZhuLei** [comment]
这个应该是浏览器配置问题，在chrome, firefox等浏览器下无此问题
