### ISSUE TITLE
想请教一下，element内置样式怎么修改

### ISSUE THREAD

**Issue by tianxia0079** [GavinZhuLei/vue-form-making#69]
比如我想对某个input调整下面的属性：
.el-input-group__prepend {
        padding: 0 10px 0 10px!important;
    }

但是我得在当前vue全局改掉，怎么只改一个input的这样式啊  谢谢大佬
这个样式是temple solt插槽自动生成的，代码里没法再添加自定义样式了呀。

**Comment by GavinZhuLei** [comment]
可以在全局定义样式在编辑器上填写class
