### ISSUE TITLE
vue打包后如何在index.html里使用封装好的axios工具类

### ISSUE THREAD

**Issue by tianxia0079** [GavinZhuLei/vue-form-making#73]
大佬请求个问题，vue打包后如何在index.html里使用封装好的axios工具类

**Comment by tianxia0079** [comment]
mian.js里约定了：
Vue.prototype.axiospost = post

可是拖拽的界面里  vue节点里，this.axiospost还是提示不存在。
大佬可以指点一下吗

**Comment by tianxia0079** [comment]
window._CONFIG['axiospost']=post
试了，也不行

**Comment by GavinZhuLei** [comment]
你这是挂载到的Vue实例上
——————————————————
请不要在这里提与该项目无关的问题
