### ISSUE TITLE
现在开源的版本，只能新增，是否有将数据带入进行修改的方法

### ISSUE THREAD

**Issue by tyjohn** [GavinZhuLei/vue-form-making#79]
![image](https://user-images.githubusercontent.com/3033456/64166093-00b90180-ce79-11e9-9b19-98b70f2f0bfe.png)

是这个方法吗？

**Comment by GavinZhuLei** [comment]
有的，使用方法请查看 http://tools.xiaoyaoji.cn/guide/generate-form.html#attributes 中 value 参数
