### ISSUE TITLE
子表单能否增加复杂表头

### ISSUE THREAD

**Issue by minghenudt** [GavinZhuLei/vue-form-making#83]
现在只能单行表头  
能够支持多行复杂表头
类似下图
![1](https://user-images.githubusercontent.com/19749909/65139833-e3229500-da3f-11e9-868b-70118cd8d9df.png)
`

**Comment by Calvin66** [comment]
你也是工程类表单吗？批量表单设计太头疼了，你有相关的解决方案吗

**Comment by GavinZhuLei** [comment]
基础版本不支持子表单，高级版本可以联系技术支持，qq:1691620947
