### ISSUE TITLE
自定义区域点击生成代码粘贴代码后怎么操作

### ISSUE THREAD

**Issue by harrisonliu5** [GavinZhuLei/vue-form-making#86]
![TIM图片20190926153817](https://user-images.githubusercontent.com/17872673/65668117-b0961f00-e073-11e9-8ed9-a7145a0279f2.png)

如图 粘贴代码后没有提交或者别的按钮进行后续操作从而生成组件

**Comment by GavinZhuLei** [comment]
复制代码保存为html即可，文档地址：http://tools.xiaoyaoji.cn/manual/custom-field.html

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by zzq0826** [comment]
是否能够通过这个html 生成json呢大佬～
