### ISSUE TITLE
异步获取下拉框数据，调用组件的this作用域在remoteFuncs怎么获取？

### ISSUE THREAD

**Issue by lliiuu** [GavinZhuLei/vue-form-making#87]

**Comment by LeoMalik** [comment]
楼主解决了么，我不知道在remoteFuncs如何使用axois方法

**Comment by lliiuu** [comment]
该怎么用就怎么用呀，只是当前组件的作用域获取不到。这是我的例子
remoteFuncs: {
func_selectCreate(resovle) {
let _this = this;
getUserStore().then(function (data) {
if (data.success) {
resovle(data.data)
}

                    })

                }

**Comment by lliiuu** [comment]
该怎么用就怎么用呀，当前组件的作用域最开始没找到方法，现在找到了，在vue组件data里面自定义一个this变量,然后在函数里面用就是了，这是我的例子
remoteFuncs: {
func_selectCreate(resovle) {
getUserStore().then(function (data) {
if (data.success) {
resovle(data.data)
}

                    })

                }
