### ISSUE TITLE
ace is not defined 

### ISSUE THREAD

**Issue by mayuanyuancode** [GavinZhuLei/vue-form-making#91]
通过npm安装，点击生成代码和生成json都会报ace is not defined，
issuess #46 中两种npm方式试了还是报错，能否告知这个报错问题的解决的方法，谢谢

**Comment by GavinZhuLei** [comment]
直接 <script src="https://unpkg.com/form-making/public/lib/ace/ace.js"></script> 引入。关于你提的文件不在，我这边检查下

**Comment by mayuanyuancode** [comment]
> 直接 <script src="https://unpkg.com/form-making/public/lib/ace/ace.js"></script> 引入。关于你提的文件不在，我这边检查下

你好，我是通过npm 包安装的，在main.js中用了两种方式引入，分别是：import 'form-making/public/lib/ace/src-min/ace.js'和'form-making/public/lib/ace/src-min-noconflict/ace.js'，但都报错了，请问应该怎么引入呢

**Comment by mayuanyuancode** [comment]
你好，我是通过npm 包安装的，在main.js中用了两种方式引入，分别是：import 'form-making/public/lib/ace/src-min/ace.js'和'form-making/public/lib/ace/src-min-noconflict/ace.js'，但都报错了，请问应该怎么引入呢

**Comment by GavinZhuLei** [comment]
更新到最新版本，import 'form-making/public/lib/ace/src-min-noconflict/ace.js' 再试下

**Comment by mayuanyuancode** [comment]
你好，功能出来了，但报了个新错误

Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver

**Comment by mayuanyuancode** [comment]
你好，另外  生成代码功能和咱们官方示例不太一样，想使用生成vue代码部分，请问是哪里的问题呢

![1573537823(1)](https://user-images.githubusercontent.com/23230893/68645807-20913380-0554-11ea-9c93-3a4e153529fb.jpg)

![1573538057(1)](https://user-images.githubusercontent.com/23230893/68645784-0bb4a000-0554-11ea-8e92-50971bcc173d.jpg)

**Comment by GavinZhuLei** [comment]
官网示例提供的是高级版本，你可以在 [这里](http://form.xiaoyaoji.cn/basic-version) 查看开源版本的演示

**Comment by mayuanyuancode** [comment]
你好，生成JSON和生成代码会报错，应该怎么解决呢

Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver

ace.js:1 GET http://localhost:9001/mode-json.js net::ERR_ABORTED 404 (Not Found)

**Comment by GavinZhuLei** [comment]
直接使用如下方式引入吧
<script src="https://unpkg.com/form-making/public/lib/ace/ace.js"></script>

**Comment by chenshouzuo** [comment]
@mayuanyuancode 你好，我也遇到跟你一样的问题，请问你的解决了吗？
