### ISSUE TITLE
在main.js中引入import 'form-making/dist/FormMaking.css' 样式没有引入进来？？？？

### ISSUE THREAD

**Issue by gexing918** [GavinZhuLei/vue-form-making#95]
`import FormMaking from 'form-making'
import 'form-making/dist/FormMaking.css'

Vue.use(FormMaking)`

**Comment by gexing918** [comment]
@GavinZhuLei 麻烦大佬看看

**Comment by GavinZhuLei** [comment]
样式是什么样的，有报错吗

**Comment by gexing918** [comment]
@GavinZhuLei 已经解决了，直接引入的`import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'`，这样就好了
