### ISSUE TITLE
引入vue-form-making，会影响到本地配置好的国际化

### ISSUE THREAD

**Issue by Alansherlock** [GavinZhuLei/vue-form-making#96]
目前的解决方案是将项目中的'zh'改为与vue-form-making一致的'zh-CN'

**Comment by GavinZhuLei** [comment]
http://docs.form.xiaoyaoji.cn/guide/i18n.html#used-in-multilingual-projects

**Comment by lxc455735702** [comment]
我也是改成了 zh-CN 才统一了
